on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: 'validate'
      uses: actions/github-script@v3.1.0
      with:
        script: |
          console.log(JSON.stringify(${{github.event}}))